### ISSUE TITLE
Create Installation Script

### ISSUE THREAD

**Issue by santakmishra** [santakmishra/recipe-manager#6]
We need to create an installation script to initialize database structure. On the front-end, we can get the database details from user and store in a file. Also, the security of this config file has to be handled properly.

**Comment by priyasonali** [comment]
I suggest lets not do this in this project. Its not a very big app and doesn't require admin control.

**Comment by santakmishra** [comment]
@priyasonali I think you're right. Implementing MVC from scratch is going to be a pain in itself. Let's not get too carried away. Dropping the installation script idea for now.
